# 04 Time Series Baseline

I read the data after the preliminary EDA performed as part of the project proposal.

In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.metrics import r2_score

I read the training and the test set.

In [2]:
X_train = np.load('X_tr_imputed.npy')
y_train = np.load('y_tr.npy')

# X_valid = np.load('features_valid.npy')
# y_valid = np.load('labels_valid.npy')

X_test = np.load('X_te_imputed.npy')
y_test = np.load('y_te.npy')

the data training and test data have One-Hot-Encoding for all categorical variables so no further processing is needed. As a first baseline would be to choose the mean values of the target vector.

In [3]:
df_tr = pd.read_pickle('training_dataset_df.csv')

I define the error functions 

In [4]:
# Mean Absolute error (MAE)
def MAE(y,y_pred):    
    return(np.mean(np.abs(y-y_pred)))

In [5]:
np.mean(y_train)

82.63073380111149

In [6]:
baseline_avg_mae = MAE(y_test, np.mean(y_train))

Since the baseline is based on the average values of the train set the coefficient of determination R^2 is zero.

In [7]:
baseline_avg_r2 = 0

A second baseline would be to choose the last hour lag of the target vector.

In [8]:
y_test.shape

(4344,)

In [9]:
y_test[:4343].shape

(4343,)

Since the .shift(1) is not supported for arrays but only for dataframes, I will equivalently take the y_train(1:4344) for the first lag of the train set. After calculating the lag (e.g. with shift(1) the first element is NaN and has to be omited.). Therefore the test set is also reduced by one sample, y_test[:4343] instead of y_test[:4344].

In [10]:
# 1st lag: y_test.shift(1)[:4343] if y_test were a dataframe
baseline_lag_mae = MAE(y_test[:4343], y_test[1:4344])
baseline_lag_r2 = r2_score(y_test[:4343], y_test[1:4344])

In [11]:
results_baseline_avg = {'model': ['baseline_avg'], 'r2_score': baseline_avg_r2, 'MAE': baseline_avg_mae}
results_baseline_lag = {'model': ['baseline_lag'], 'r2_score': baseline_lag_r2, 'MAE': baseline_lag_mae}

results_baseline_avg = pd.DataFrame(results_baseline_avg)
results_baseline_lag = pd.DataFrame(results_baseline_lag)

np.save('results_baseline_avg', results_baseline_avg)
np.save('results_baseline_lag', results_baseline_lag)

In [12]:
results_baseline_avg

model  r2_score        MAE
0  baseline_avg         0  78.770295

A r2 score of 0 means that the model and the estimator have the same performance which is the case here. The estimator baseline_avg is actually the baseline used for the r2 score.

In [13]:
results_baseline_lag

model  r2_score        MAE
0  baseline_lag  0.942308  12.366245

a r2 score close to 1 indicates that the estimator, in this case the baseline_avg iperforms way better than the baselien (baseline_avg). The MAE score is much less than in hte previous case.